(load "~/.emacs.d/init/emacs-init-1.el")
(load "~/.emacs.d/init/emacs-init-2.el")
(load "~/.emacs.d/init/emacs-init-3.el")
(load "~/.emacs.d/init/emacs-init-4.el")
(load "~/.emacs.d/init/emacs-init-5.el")
